"""utils/export_share.py
─────────────────────
Helpers to export combat CSVs and generate a small GIF "replay" for a single
combat. Kept isolated so Streamlit views can import and call these helpers.
"""

from io import BytesIO
from typing import Optional

import pandas as pd


def combat_csv_bytes(combat_df: pd.DataFrame) -> bytes:
    """Return CSV bytes for the supplied combat DataFrame."""
    return combat_df.to_csv(index=False).encode("utf-8")


def create_combat_gif_bytes(combat_df: pd.DataFrame, max_bars: int = 5, fps: int = 6) -> Optional[bytes]:
    """Create a simple GIF replay showing cumulative damage over time.

    - Uses Pillow if available to render frames; returns None when Pillow is
      not installed or if the DataFrame is empty.
    - The GIF shows top `max_bars` sources by final damage and their
      cumulative damage growing over time.
    """
    if combat_df is None or combat_df.empty:
        return None

    try:
        from PIL import Image, ImageDraw, ImageFont
    except Exception:
        return None

    # Prepare time series (elapsed seconds) and damage-only events
    if "timestamp_dt" not in combat_df.columns:
        return None
    df = combat_df.copy()
    start = df["timestamp_dt"].min()
    df["elapsed_s"] = (df["timestamp_dt"] - start).dt.total_seconds()
    dmg = df[df["type"] == "damage"].copy()
    if dmg.empty:
        return None

    # Final totals by source to pick top bars
    totals = dmg.groupby("source")["effective_amount"].sum().sort_values(ascending=False)
    top_sources = totals.head(max_bars).index.tolist()
    if not top_sources:
        return None

    # Time frames: one frame per second, capped to 120s to avoid huge GIFs
    duration = int(max(1, df["elapsed_s"].max()))
    n_frames = min(120, duration + 1)
    times = list(range(n_frames))

    # Canvas settings
    W, H = 640, 240
    pad = 12
    bar_h = int((H - 2 * pad) / max_bars) - 6

    # Basic font fallback
    try:
        font = ImageFont.load_default()
    except Exception:
        font = None

    frames = []
    final_max = totals.loc[top_sources].max()
    for t in times:
        # cumulative sums up to t
        cum = dmg[dmg["elapsed_s"] <= t].groupby("source")["effective_amount"].sum().reindex(top_sources).fillna(0)
        img = Image.new("RGB", (W, H), "#0f1720")
        draw = ImageDraw.Draw(img)

        # Title
        title = f"Replay — t={t}s"
        draw.text((pad, 6), title, fill="#ffffff", font=font)

        # Draw bars
        for i, src in enumerate(top_sources):
            val = float(cum.get(src, 0))
            frac = val / final_max if final_max > 0 else 0.0
            bar_w = int((W - 220) * frac)
            y = pad + 28 + i * (bar_h + 6)
            # background bar
            draw.rectangle([110, y, 110 + (W - 220), y + bar_h], fill="#22303a")
            # foreground
            draw.rectangle([110, y, 110 + bar_w, y + bar_h], fill="#7CFC00")
            # labels
            label = str(src).split("-")[0]
            draw.text((6, y + (bar_h // 4)), label, fill="#cbd5e1", font=font)
            draw.text((120 + (W - 220) + 6, y + (bar_h // 4)), f"{int(val):,}", fill="#ffffff", font=font)

        # Footer note
        draw.text((pad, H - 16), "Generated by WoW Combat Viewer — simple replay", fill="#94a3b8", font=font)

        frames.append(img)

    # Save to GIF bytes
    bio = BytesIO()
    try:
        frames[0].save(
            bio,
            format="GIF",
            save_all=True,
            append_images=frames[1:],
            duration=int(1000 / fps),
            loop=0,
            optimize=False,
        )
    except Exception:
        return None

    return bio.getvalue()


def register_share_ui(combat_df, combat_id):
    """Streamlit small UI helper: CSV download and GIF replay generator.

    This helper imports Streamlit lazily so the module can be imported in
    non-Streamlit contexts.
    """
    try:
        import streamlit as st
    except Exception:
        return

    with st.expander("Share / Export", expanded=False):
        # CSV download for the selected combat
        csv_bytes = combat_csv_bytes(combat_df)
        st.download_button(
            "Download combat CSV",
            csv_bytes,
            file_name=f"combat_{combat_id}.csv",
            mime="text/csv",
            key=f"dl_combat_csv_{combat_id}",
        )

        st.write("---")
        gen_key = f"gen_gif_{combat_id}"
        state_key = f"gif_bytes_{combat_id}"

        if st.button("Generate GIF replay", key=gen_key):
            with st.spinner("Generating GIF..."):
                gif_bytes = create_combat_gif_bytes(combat_df)
                if gif_bytes is None:
                    st.info("GIF generation unavailable — missing Pillow or no damage events.")
                    if state_key in st.session_state:
                        del st.session_state[state_key]
                else:
                    # Store in session state so a rerun (or autorefresh) doesn't lose it
                    st.session_state[state_key] = gif_bytes

        # If we have generated bytes in session, show a direct download button
        if st.session_state.get(state_key):
            gif_bytes = st.session_state[state_key]
            st.success("GIF ready — click to download")
            st.download_button(
                "Download GIF",
                gif_bytes,
                file_name=f"combat_{combat_id}.gif",
                mime="image/gif",
                key=f"dl_gif_{combat_id}",
            )
